spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/discodeit
    username: postgres
    password: System1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false